/* ============================================================
   Genios y Gigantes — Arquetipos (cartas de personaje)
   Cada carta: efectos de Ascenso / Influencia / Herencia.
   `fx` codifica lo que el motor puede automatizar.
   ============================================================ */
window.GG = window.GG || {};

GG.ARCHETYPES = [
  /* ---------------- MILITARES ---------------- */
  { id: "M1", block: "Militar", name: "El Conquistador", character: "Alejandro Magno", points: 4, duration: 3,
    ascenso: "Recluta 2 cohortes.", influencia: "+2 en ataques.", herencia: "Ninguna.",
    fx: { ascension: { recruit: 2 }, influence: { attack: 2 } } },
  { id: "M2", block: "Militar", name: "El Organizador Militar", character: "Cayo Mario", points: 2, duration: 4,
    ascenso: "Ninguno.", influencia: "Reclutas una cohorte gratis por turno.", herencia: "+1 Poder permanente.",
    fx: { influence: { freeRecruitPerTurn: 1 }, legacy: { pillars: { poder: 1 } } } },
  { id: "M3", block: "Militar", name: "El Genio Táctico", character: "Aníbal", points: 3, duration: 3,
    ascenso: "Ninguno.", influencia: "+3 cuando enfrentas a un enemigo con más cohortes.", herencia: "Ninguna.",
    fx: { influence: { battleVsLarger: 3 } } },
  { id: "M4", block: "Militar", name: "El Organizador Militar (movilidad)", character: "Belisario", points: 2, duration: 4,
    ascenso: "Obtén 2 Armas.", influencia: "Tus cohortes pueden desplazarse hasta 2 provincias por turno.", herencia: "Ninguna.",
    fx: { ascension: { resources: { armas: 2 } }, influence: { moveMax: 2 } } },
  { id: "M5", block: "Militar", name: "El Defensor", character: "Leónidas", points: 3, duration: 4,
    ascenso: "Ninguno.", influencia: "+2 en batallas defensivas.", herencia: "Ninguna.",
    fx: { influence: { defense: 2 } } },
  { id: "M6", block: "Militar", name: "El Militarista", character: "Federico el Grande", points: 2, duration: 3,
    ascenso: "Obtén 3 armas.", influencia: "+1 Poder y +1 Ciencia.", herencia: "Ninguna.",
    fx: { ascension: { resources: { armas: 3 } }, influence: { pillars: { poder: 1, ciencia: 1 } } } },
  { id: "M7", block: "Militar", name: "El Forjador de Imperios", character: "Julio César", points: 4, duration: 4,
    ascenso: "Obtén una provincia neutral o enemiga (sin ciudad) adyacente sin pagar piedra.", influencia: "+2 en todas las batallas.", herencia: "Ninguna.",
    fx: { ascension: { occupyFreeAdjacent: true }, influence: { allBattle: 2 } } },
  { id: "M8", block: "Militar", name: "El Destructor", character: "Gengis Kan", points: 3, duration: 2,
    ascenso: "Recluta 4 cohortes.", influencia: "+3 en ataque.", herencia: "-1 Libertad.",
    fx: { ascension: { recruit: 4 }, influence: { attack: 3 }, legacy: { pillars: { libertad: -1 } } } },

  /* ---------------- POLÍTICOS ---------------- */
  { id: "P1", block: "Político", name: "El Administrador", character: "Mansa Musa", points: 3, duration: 4,
    ascenso: "Obtén 3 Oro.", influencia: "Produces +1 Oro por turno.", herencia: "Ninguna.",
    fx: { ascension: { resources: { oro: 3 } }, influence: { goldPerTurn: 1 } } },
  { id: "P2", block: "Político", name: "El Reformador", character: "Augusto", points: 4, duration: 3,
    ascenso: "Cambia de gobierno gratuitamente.", influencia: "El efecto de tu gobierno se duplica.", herencia: "Ninguna.",
    fx: { ascension: { freeGov: true }, influence: { govDoubled: true } } },
  { id: "P3", block: "Político", name: "El Centralizador", character: "Luis XIV", points: 4, duration: 4,
    ascenso: "Ninguno.", influencia: "+3 Poder.", herencia: "-1 Libertad permanente.",
    fx: { influence: { pillars: { poder: 3 } }, legacy: { pillars: { libertad: -1 } } } },
  { id: "P4", block: "Político", name: "Constructor de Estados", character: "Catalina la Grande", points: 3, duration: 4,
    ascenso: "Obtén 2 Piedra.", influencia: "Las ciudades cuestan 2 menos de Oro y Piedra.", herencia: "Ninguna.",
    fx: { ascension: { resources: { piedra: 2 } }, influence: { cityCostReduce: { oro: 2, piedra: 2 } } } },
  { id: "P5", block: "Político", name: "El Recaudador", character: "Cosme de Médici", points: 2, duration: 3,
    ascenso: "Ninguno.", influencia: "Al inicio de cada turno obtienes 2 Oro por cada ciudad que controles.", herencia: "Ninguna.",
    fx: { influence: { goldPerCityPerTurn: 2 } } },
  { id: "P6", block: "Político", name: "El Codificador", character: "Hammurabi", points: 2, duration: 3,
    ascenso: "Ninguno.", influencia: "Cada vez que aumentes un pilar mediante pago de recursos, paga 1 recurso menos.", herencia: "+1 Cultura permanente.",
    fx: { influence: { pillarPayDiscount: 1 }, legacy: { pillars: { cultura: 1 } } } },
  { id: "P7", block: "Político", name: "El Diplomático", character: "Marco Polo", points: 2, duration: 3,
    ascenso: "Obtén 2 Oro.", influencia: "Comercias con el mercader en proporción 1:1.", herencia: "Ninguna.",
    fx: { ascension: { resources: { oro: 2 } }, influence: { merchant1to1: true } } },
  { id: "P8", block: "Político", name: "El Integrador", character: "Carlomagno", points: 4, duration: 4,
    ascenso: "Ninguno.", influencia: "Las provincias conquistadas producen recursos inmediatamente.", herencia: "+1 Poder permanente.",
    fx: { influence: { produceConqueredImmediately: true }, legacy: { pillars: { poder: 1 } } } },

  /* ---------------- CIENCIA ---------------- */
  { id: "C1", block: "Ciencia", name: "El Inventor", character: "Nikola Tesla", points: 3, duration: 3,
    ascenso: "Ninguno.", influencia: "+3 Ciencia.", herencia: "+1 Ciencia permanente.",
    fx: { influence: { pillars: { ciencia: 3 } }, legacy: { pillars: { ciencia: 1 } } } },
  { id: "C2", block: "Ciencia", name: "El Ingeniero", character: "Arquímedes", points: 2, duration: 4,
    ascenso: "Obtén 3 Piedra.", influencia: "Todas las construcciones cuestan 1 recurso menos.", herencia: "Ninguna.",
    fx: { ascension: { resources: { piedra: 3 } }, influence: { allBuildReduce: 1 } } },
  { id: "C3", block: "Ciencia", name: "El Visionario", character: "Galileo Galilei", points: 4, duration: 3,
    ascenso: "Ninguno.", influencia: "+2 Ciencia, +1 Cultura.", herencia: "Ninguna.",
    fx: { influence: { pillars: { ciencia: 2, cultura: 1 } } } },
  { id: "C4", block: "Ciencia", name: "El Estratega Científico", character: "Alan Turing", points: 2, duration: 4,
    ascenso: "Ninguno.", influencia: "Tu Ciencia aporta el doble en las batallas.", herencia: "Ninguna.",
    fx: { influence: { scienceDoubleBattle: true } } },
  { id: "C5", block: "Ciencia", name: "El Arquitecto", character: "Filippo Brunelleschi", points: 2, duration: 3,
    ascenso: "Obtén 2 Piedra.", influencia: "Una ciudad a tu elección produce un recurso adicional.", herencia: "Esa ciudad conserva el bono mientras permanezca bajo tu control.",
    fx: { ascension: { resources: { piedra: 2 } }, influence: { cityExtraResource: true } } },
  { id: "C6", block: "Ciencia", name: "El Precursor", character: "Isaac Newton", points: 3, duration: 3,
    ascenso: "Ninguno.", influencia: "Una vez por turno puedes aumentar un pilar pagando 1 recurso menos.", herencia: "Ninguna.",
    fx: { influence: { oncePillarDiscount: 1 } } },

  /* ---------------- CULTURA ---------------- */
  { id: "CU1", block: "Cultura", name: "El Mecenas", character: "Lorenzo de Médici", points: 2, duration: 3,
    ascenso: "Obtén 2 Oro.", influencia: "+3 Cultura.", herencia: "Ninguna.",
    fx: { ascension: { resources: { oro: 2 } }, influence: { pillars: { cultura: 3 } } } },
  { id: "CU2", block: "Cultura", name: "El Humanista", character: "Leonardo da Vinci", points: 3, duration: 4,
    ascenso: "Ninguno.", influencia: "+1 Ciencia, +1 Cultura, +1 Libertad.", herencia: "Ninguna.",
    fx: { influence: { pillars: { ciencia: 1, cultura: 1, libertad: 1 } } } },
  { id: "CU3", block: "Cultura", name: "El Artista Universal", character: "Miguel de Cervantes", points: 3, duration: 3,
    ascenso: "Ninguno.", influencia: "+2 Cultura.", herencia: "+1 Cultura permanente.",
    fx: { influence: { pillars: { cultura: 2 } }, legacy: { pillars: { cultura: 1 } } } },
  { id: "CU4", block: "Cultura", name: "El Propagandista", character: "Confucio", points: 2, duration: 3,
    ascenso: "Ninguno.", influencia: "+2 Poder, +1 Cultura.", herencia: "Ninguna.",
    fx: { influence: { pillars: { poder: 2, cultura: 1 } } } },
  { id: "CU5", block: "Cultura", name: "El Cosmopolita", character: "Ibn Battuta", points: 2, duration: 4,
    ascenso: "Obtén 2 Oro.", influencia: "Puedes comerciar con el mercader en proporción 1:1.", herencia: "+1 Cultura permanente.",
    fx: { ascension: { resources: { oro: 2 } }, influence: { merchant1to1: true }, legacy: { pillars: { cultura: 1 } } } },

  /* ---------------- RELIGIÓN ---------------- */
  { id: "R1", block: "Religión", name: "El Profeta", character: "Mahoma", points: 4, duration: 3,
    ascenso: "Cambia inmediatamente de religión.", influencia: "+2 Libertad.", herencia: "Ninguna.",
    fx: { ascension: { changeReligion: true }, influence: { pillars: { libertad: 2 } } } },
  { id: "R2", block: "Religión", name: "El Reformador Religioso", character: "Martín Lutero", points: 3, duration: 4,
    ascenso: "Cambia inmediatamente de religión.", influencia: "+2 Cultura.", herencia: "+1 Libertad permanente.",
    fx: { ascension: { changeReligion: true }, influence: { pillars: { cultura: 2 } }, legacy: { pillars: { libertad: 1 } } } },
  { id: "R3", block: "Religión", name: "El Fanático", character: "Tomás de Torquemada", points: 2, duration: 3,
    ascenso: "Obtén 2 Armas.", influencia: "+3 Poder.", herencia: "-1 Cultura permanente.",
    fx: { ascension: { resources: { armas: 2 } }, influence: { pillars: { poder: 3 } }, legacy: { pillars: { cultura: -1 } } } },
  { id: "R4", block: "Religión", name: "El Pacificador", character: "Buda", points: 3, duration: 2,
    ascenso: "Obtén 2 Comida.", influencia: "No puedes declarar ataques; los demás no pueden atacarte.", herencia: "+1 Cultura permanente.",
    fx: { ascension: { resources: { alimentos: 2 } }, influence: { noAttackPeace: true }, legacy: { pillars: { cultura: 1 } } } },
  { id: "R5", block: "Religión", name: "El Teólogo", character: "Santo Tomás de Aquino", points: 2, duration: 3,
    ascenso: "Ninguno.", influencia: "+1 Ciencia, +1 Cultura.", herencia: "Ninguna.",
    fx: { influence: { pillars: { ciencia: 1, cultura: 1 } } } },

  /* ---------------- REBELDES ---------------- */
  { id: "V1", block: "Rebelde", name: "El Libertador", character: "Simón Bolívar", points: 4, duration: 3,
    ascenso: "Puedes iniciar inmediatamente una Guerra de Liberación.", influencia: "+3 Libertad.", herencia: "Ninguna.",
    fx: { ascension: { liberationWar: true }, influence: { pillars: { libertad: 3 } } } },
  { id: "V2", block: "Rebelde", name: "El Agitador", character: "Che Guevara", points: 3, duration: 2,
    ascenso: "Ninguno.", influencia: "Elige un rival. Ese rival recibe -2 Poder.", herencia: "Ninguna.",
    fx: { influence: { enemyPowerMinus: 2 } } },
  { id: "V3", block: "Rebelde", name: "El Tribuno", character: "Tiberio Graco", points: 2, duration: 3,
    ascenso: "Ninguno.", influencia: "Puedes aumentar Libertad pagando únicamente 5 Comida en lugar de 7.", herencia: "+1 Libertad permanente.",
    fx: { influence: { libertadPayFood: 5 }, legacy: { pillars: { libertad: 1 } } } },
  { id: "V4", block: "Rebelde", name: "El Insurgente", character: "William Wallace", points: 3, duration: 3,
    ascenso: "Recluta 2 cohortes. Puedes iniciar inmediatamente una Guerra de Liberación.", influencia: "+1 Libertad.", herencia: "Ninguna.",
    fx: { ascension: { recruit: 2, liberationWar: true }, influence: { pillars: { libertad: 1 } } } },

  /* ---------------- VILLANOS / CAOS ---------------- */
  { id: "X1", block: "Villano", name: "El Tirano", character: "Josef Stalin", points: 3, duration: 4,
    ascenso: "Obtén 3 Oro.", influencia: "+3 Poder.", herencia: "-1 Libertad permanente.",
    fx: { ascension: { resources: { oro: 3 } }, influence: { pillars: { poder: 3 } }, legacy: { pillars: { libertad: -1 } } } },
  { id: "X2", block: "Villano", name: "El Corrupto", character: "Nerón", points: 2, duration: 3,
    ascenso: "Obtén 5 Oro.", influencia: "+1 Poder.", herencia: "-1 Cultura permanente.",
    fx: { ascension: { resources: { oro: 5 } }, influence: { pillars: { poder: 1 } }, legacy: { pillars: { cultura: -1 } } } },
  { id: "X3", block: "Villano", name: "El Purgador", character: "Mao Zedong", points: 3, duration: 3,
    ascenso: "Obtén 2 Armas.", influencia: "+2 Poder, +1 Ciencia.", herencia: "-1 Cultura permanente.",
    fx: { ascension: { resources: { armas: 2 } }, influence: { pillars: { poder: 2, ciencia: 1 } }, legacy: { pillars: { cultura: -1 } } } },
  { id: "X4", block: "Villano", name: "El Demagogo", character: "Juan Domingo Perón", points: 3, duration: 3,
    ascenso: "+1 Libertad.", influencia: "+2 Poder, +1 Libertad.", herencia: "-1 Poder permanente.",
    fx: { ascension: { pillars: { libertad: 1 } }, influence: { pillars: { poder: 2, libertad: 1 } }, legacy: { pillars: { poder: -1 } } } },
];
