/* ============================================================
   Genios y Gigantes — Cartas de Situación
   copies = cantidad de copias en el mazo.
   fx = efecto automatizable; manual=true => se aplica/recuerda
   con texto (efectos que requieren decisión sobre el tablero).
   ============================================================ */
window.GG = window.GG || {};

GG.SITUATIONS = [
  /* ---------------- MUY COMUNES ---------------- */
  { id: "auge_comercial",     name: "Auge Comercial",            rarity: "muy_comun", copies: 2, text: "+3 Oro.",       fx: { res: { oro: 3 } } },
  { id: "tributo_extra",      name: "Tributo Extraordinario",    rarity: "muy_comun", copies: 2, text: "+3 Oro.",       fx: { res: { oro: 3 } } },
  { id: "cosecha_abundante",  name: "Cosecha Abundante",         rarity: "muy_comun", copies: 2, text: "+3 Alimentos.", fx: { res: { alimentos: 3 } } },
  { id: "rebanos_prosperos",  name: "Rebaños Prósperos",         rarity: "muy_comun", copies: 2, text: "+3 Alimentos.", fx: { res: { alimentos: 3 } } },
  { id: "nueva_cantera",      name: "Nueva Cantera",             rarity: "muy_comun", copies: 2, text: "+3 Piedra.",    fx: { res: { piedra: 3 } } },
  { id: "marmol_superior",    name: "Mármol de Calidad Superior",rarity: "muy_comun", copies: 2, text: "+3 Piedra.",    fx: { res: { piedra: 3 } } },
  { id: "industria_belica",   name: "Industria Bélica",          rarity: "muy_comun", copies: 2, text: "+3 Armas.",     fx: { res: { armas: 3 } } },
  { id: "forjas_marcha",      name: "Forjas a Plena Marcha",     rarity: "muy_comun", copies: 2, text: "+3 Armas.",     fx: { res: { armas: 3 } } },
  { id: "colapso_financiero", name: "Colapso Financiero",        rarity: "muy_comun", copies: 2, text: "-3 Oro.",       fx: { res: { oro: -3 } } },
  { id: "corrupcion_gen",     name: "Corrupción Generalizada",   rarity: "muy_comun", copies: 2, text: "-3 Oro.",       fx: { res: { oro: -3 } } },
  { id: "gran_hambruna",      name: "Gran Hambruna",             rarity: "muy_comun", copies: 2, text: "-3 Alimentos.", fx: { res: { alimentos: -3 } } },
  { id: "plaga_cosechas",     name: "Plaga en las Cosechas",     rarity: "muy_comun", copies: 2, text: "-3 Alimentos.", fx: { res: { alimentos: -3 } } },
  { id: "derrumbe_canteras",  name: "Derrumbe en las Canteras",  rarity: "muy_comun", copies: 2, text: "-3 Piedra.",    fx: { res: { piedra: -3 } } },
  { id: "agotamiento_yac",    name: "Agotamiento de Yacimientos",rarity: "muy_comun", copies: 2, text: "-3 Piedra.",    fx: { res: { piedra: -3 } } },
  { id: "sabotaje_forjas",    name: "Sabotaje en las Forjas",    rarity: "muy_comun", copies: 2, text: "-3 Armas.",     fx: { res: { armas: -3 } } },
  { id: "robo_arsenales",     name: "Robo de Arsenales",         rarity: "muy_comun", copies: 2, text: "-3 Armas.",     fx: { res: { armas: -3 } } },
  { id: "descubrimiento_menor",name:"Descubrimiento Menor",      rarity: "muy_comun", copies: 1, text: "+1 Ciencia.",  fx: { pillars: { ciencia: 1 } } },
  { id: "revolucion_cientifica",name:"Revolución Científica",    rarity: "muy_comun", copies: 1, text: "+2 Ciencia.",  fx: { pillars: { ciencia: 2 } } },
  { id: "censura_intelectual",name: "Censura Intelectual",       rarity: "muy_comun", copies: 1, text: "-1 Ciencia.",  fx: { pillars: { ciencia: -1 } } },
  { id: "quema_bibliotecas",  name: "Quema de Bibliotecas",      rarity: "muy_comun", copies: 1, text: "-2 Ciencia.",  fx: { pillars: { ciencia: -2 } } },
  { id: "festival_popular",   name: "Festival Popular",          rarity: "muy_comun", copies: 1, text: "+1 Cultura.",  fx: { pillars: { cultura: 1 } } },
  { id: "renacimiento_art",   name: "Renacimiento Artístico",    rarity: "muy_comun", copies: 1, text: "+2 Cultura.",  fx: { pillars: { cultura: 2 } } },
  { id: "decadencia_cultural",name: "Decadencia Cultural",       rarity: "muy_comun", copies: 1, text: "-1 Cultura.",  fx: { pillars: { cultura: -1 } } },
  { id: "iconoclasia",        name: "Iconoclasia",               rarity: "muy_comun", copies: 1, text: "-2 Cultura.",  fx: { pillars: { cultura: -2 } } },
  { id: "reformas_civiles",   name: "Reformas Civiles",          rarity: "muy_comun", copies: 1, text: "+1 Libertad.", fx: { pillars: { libertad: 1 } } },
  { id: "declaracion_derechos",name:"Declaración de Derechos",   rarity: "muy_comun", copies: 1, text: "+2 Libertad.", fx: { pillars: { libertad: 2 } } },
  { id: "estado_excepcion",   name: "Estado de Excepción",       rarity: "muy_comun", copies: 1, text: "-1 Libertad.", fx: { pillars: { libertad: -1 } } },
  { id: "represion_gen",      name: "Represión Generalizada",    rarity: "muy_comun", copies: 1, text: "-2 Libertad.", fx: { pillars: { libertad: -2 } } },
  { id: "centralizacion_adm", name: "Centralización Administrativa",rarity:"muy_comun",copies:1, text: "+1 Poder.",    fx: { pillars: { poder: 1 } } },
  { id: "aires_totalitarismo",name: "Aires de Totalitarismo",    rarity: "muy_comun", copies: 1, text: "+2 Poder.",    fx: { pillars: { poder: 2 } } },
  { id: "escandalo_gub",      name: "Escándalo Gubernamental",   rarity: "muy_comun", copies: 1, text: "-1 Poder.",    fx: { pillars: { poder: -1 } } },
  { id: "crisis_institucional",name:"Crisis Institucional",      rarity: "muy_comun", copies: 1, text: "-2 Poder.",    fx: { pillars: { poder: -2 } } },
  { id: "reformas_educativas",name: "Reformas Educativas",       rarity: "muy_comun", copies: 1, text: "+1 Ciencia, -1 Poder.",    fx: { pillars: { ciencia: 1, poder: -1 } } },
  { id: "militarizacion_est", name: "Militarización del Estado", rarity: "muy_comun", copies: 1, text: "+1 Poder, -1 Libertad.",   fx: { pillars: { poder: 1, libertad: -1 } } },
  { id: "mecenazgo_estatal",  name: "Mecenazgo Estatal",         rarity: "muy_comun", copies: 1, text: "+1 Cultura, -1 Ciencia.",  fx: { pillars: { cultura: 1, ciencia: -1 } } },
  { id: "industrializacion",  name: "Industrialización Acelerada",rarity:"muy_comun", copies: 1, text: "+1 Ciencia, -1 Cultura.",  fx: { pillars: { ciencia: 1, cultura: -1 } } },
  { id: "nacionalismo_pop",   name: "Nacionalismo Popular",      rarity: "muy_comun", copies: 1, text: "+1 Poder, -1 Ciencia.",    fx: { pillars: { poder: 1, ciencia: -1 } } },
  { id: "movimiento_reformista",name:"Movimiento Reformista",    rarity: "muy_comun", copies: 1, text: "+1 Libertad, -1 Poder.",   fx: { pillars: { libertad: 1, poder: -1 } } },
  { id: "tradicion_conservadora",name:"Tradición Conservadora",  rarity: "muy_comun", copies: 1, text: "+1 Cultura, -1 Libertad.", fx: { pillars: { cultura: 1, libertad: -1 } } },
  { id: "liberalizacion_econ",name: "Liberalización Económica",  rarity: "muy_comun", copies: 1, text: "+1 Libertad, -1 Cultura.", fx: { pillars: { libertad: 1, cultura: -1 } } },
  { id: "levantamiento_patrio",name:"Levantamiento Patriótico",  rarity: "muy_comun", copies: 1, text: "+3 Cohortes.", fx: { cohorts: 3 } },
  { id: "fiebre_reclutamiento",name:"Fiebre del Reclutamiento",  rarity: "muy_comun", copies: 1, text: "+3 Cohortes.", fx: { cohorts: 3 } },
  { id: "fatiga_guerra",      name: "Fatiga de Guerra",          rarity: "muy_comun", copies: 1, text: "-3 Cohortes.", fx: { cohorts: -3 } },
  { id: "plaga_campamento",   name: "Plaga de Campamento",       rarity: "muy_comun", copies: 1, text: "-3 Cohortes.", fx: { cohorts: -3 } },
  { id: "cartografos_reales", name: "Cartógrafos reales",        rarity: "muy_comun", copies: 1, text: "Este turno puedes ocupar provincias sin pagar piedra.", fx: { self: { freeOccupy: true } } },
  { id: "arquitectos_vis",    name: "Arquitectos visionarios",   rarity: "muy_comun", copies: 1, text: "El coste de construir una ciudad se reduce en un tercio este turno.", fx: { self: { cityDiscountThird: true } } },
  { id: "anio_tranquilo",     name: "Un año tranquilo",          rarity: "muy_comun", copies: 5, text: "Sin efecto.", fx: { noEffect: true } },
  { id: "embajada_comercial", name: "Embajada comercial",        rarity: "muy_comun", copies: 1, text: "Realiza inmediatamente un intercambio 1:1 de hasta 3 unidades de recursos con un jugador de tu elección.", fx: { manual: true } },

  /* ---------------- COMUNES ---------------- */
  { id: "nace_leyenda",       name: "Nace una Leyenda",          rarity: "comun", copies: 2, text: "Obtienes carta de Genios y Gigantes.", fx: { drawGyG: true } },
  { id: "tiempo_gigantes",    name: "Tiempo de Gigantes",        rarity: "comun", copies: 2, text: "Obtienes carta de Genios y Gigantes.", fx: { drawGyG: true } },
  { id: "general_inspirador", name: "General Inspirador",        rarity: "comun", copies: 2, text: "+2 a las tiradas de combate hasta tu próximo turno.", fx: { self: { combatMod: 2 } } },
  { id: "espiritu_victoria",  name: "Espíritu de Victoria",      rarity: "comun", copies: 1, text: "+2 a las tiradas de combate hasta tu próximo turno.", fx: { self: { combatMod: 2 } } },
  { id: "traicion_mercenarios",name:"Traición de los mercenarios",rarity:"comun", copies: 2, text: "-2 a las tiradas de combate hasta tu próximo turno.", fx: { self: { combatMod: -2 } } },
  { id: "motin_filas",        name: "Motín en las Filas",        rarity: "comun", copies: 1, text: "-2 a las tiradas de combate hasta tu próximo turno.", fx: { self: { combatMod: -2 } } },
  { id: "milicias_locales",   name: "Milicias Locales",          rarity: "comun", copies: 1, text: "Las provincias sin cohortes se defienden como si tuvieran 2 cohortes.", fx: { self: { provDefGhost: 2 } } },
  { id: "marcha_forzada",     name: "Marcha Forzada",            rarity: "comun", copies: 2, text: "Tus cohortes pueden mover hasta 2 provincias este turno.", fx: { self: { moveMax: 2 } } },
  { id: "leva_obligatoria",   name: "Leva Obligatoria",          rarity: "comun", copies: 2, text: "Las cohortes no cuestan oro este turno.", fx: { self: { recruitNoGold: true } } },
  { id: "resistencia_servicio",name:"Resistencia al Servicio Militar",rarity:"comun",copies:1,text:"Las cohortes cuestan el doble de oro y armas este turno.", fx: { self: { recruitDouble: true } } },
  { id: "embargo_comercial",  name: "Embargo Comercial",         rarity: "comun", copies: 1, text: "No puedes comerciar hasta tu próximo turno.", fx: { self: { noTrade: true } } },
  { id: "pirateria_gen",      name: "Piratería Generalizada",    rarity: "comun", copies: 1, text: "Ningún jugador puede comerciar hasta la próxima ronda.", fx: { global: { noTradeAll: true } } },
  { id: "guerra_arancelaria", name: "Guerra Arancelaria",        rarity: "comun", copies: 2, text: "Elige dos jugadores. No pueden comerciar entre sí en su próximo turno.", fx: { manual: true } },
  { id: "crecimiento_demografico",name:"Crecimiento Demográfico",rarity:"comun", copies: 2, text: "Tus ciudades producen +1 recurso durante la próxima ronda.", fx: { self: { cityProdBonus: 1 } } },
  { id: "crisis_mano_obra",   name: "Crisis de Mano de Obra",    rarity: "comun", copies: 1, text: "Ningún jugador puede construir durante la próxima ronda.", fx: { global: { noBuildAll: true } } },
  { id: "anios_tranquilos",   name: "Años Tranquilos",           rarity: "comun", copies: 1, text: "Ningún jugador toma carta de situación en su próximo turno.", fx: { global: { noSituationAll: true } } },
  { id: "guerra_trincheras",  name: "Guerra de Trincheras",      rarity: "comun", copies: 1, text: "Durante la próxima ronda solo se permiten movimientos de invasión.", fx: { global: { onlyInvasion: true } } },
  { id: "explotacion_intensiva",name:"Explotación Intensiva",    rarity: "comun", copies: 1, text: "+4 Piedra, -1 Libertad.",   fx: { res: { piedra: 4 }, pillars: { libertad: -1 } } },
  { id: "impuestos_emergencia",name:"Impuestos de Emergencia",   rarity: "comun", copies: 1, text: "+4 Oro, -1 Libertad.",      fx: { res: { oro: 4 }, pillars: { libertad: -1 } } },
  { id: "reclutamiento_forzoso",name:"Reclutamiento Forzoso",    rarity: "comun", copies: 1, text: "+4 Armas, -1 Cultura.",     fx: { res: { armas: 4 }, pillars: { cultura: -1 } } },
  { id: "racionamiento_estatal",name:"Racionamiento Estatal",    rarity: "comun", copies: 1, text: "+4 Alimentos, -1 Poder.",   fx: { res: { alimentos: 4 }, pillars: { poder: -1 } } },
  { id: "educacion_privada",  name: "Educación Privada",         rarity: "comun", copies: 1, text: "+4 Oro, -1 Ciencia.",       fx: { res: { oro: 4 }, pillars: { ciencia: -1 } } },
  { id: "saqueo_monumentos",  name: "Saqueo de Monumentos",      rarity: "comun", copies: 1, text: "+4 Piedra, -1 Cultura.",    fx: { res: { piedra: 4 }, pillars: { cultura: -1 } } },
  { id: "militarizacion_econ",name: "Militarización de la Economía",rarity:"comun",copies:1, text: "+4 Armas, -1 Ciencia.",     fx: { res: { armas: 4 }, pillars: { ciencia: -1 } } },
  { id: "conversion_tierras", name: "Conversión de Tierras de Cultivo",rarity:"comun",copies:1,text:"+4 Alimentos, -1 Poder.",   fx: { res: { alimentos: 4 }, pillars: { poder: -1 } } },

  /* ---------------- RARAS ---------------- */
  { id: "levantamiento_popular",name:"Levantamiento Popular",    rarity: "rara", copies: 2, text: "Una provincia de tu elección, en el límite con otro jugador, se vuelve neutral.", fx: { manual: true } },
  { id: "revuelta_esclavos",  name: "Revuelta de esclavos",      rarity: "rara", copies: 2, text: "Una provincia de tu elección, en frontera, se rebela. Obtiene 2 cohortes rebeldes.", fx: { manual: true } },
  { id: "traicion_gobernador",name: "Traición del Gobernador",   rarity: "rara", copies: 2, text: "El jugador de tu derecha toma una provincia tuya de frontera sin cohortes.", fx: { manual: true } },
  { id: "murallas_inexpugnables",name:"Murallas Inexpugnables",  rarity: "rara", copies: 1, text: "Todos los asedios en curso duran 1 turno más.", fx: { sieges: { delta: 1 } } },
  { id: "hambruna_ciudad",    name: "Hambruna en la Ciudad",     rarity: "rara", copies: 1, text: "Todos los asedios en curso duran 1 turno menos.", fx: { sieges: { delta: -1 } } },
  { id: "guarnicion_rinde",   name: "La Guarnición se Rinde",    rarity: "rara", copies: 1, text: "Todos los asedios en curso finalizan ya, con victoria para el atacante.", fx: { sieges: { resolve: true } } },
  { id: "mercenarios_contratados",name:"Mercenarios Contratados",rarity:"rara", copies: 1, text: "Todo ejército asediante recibe 2 cohortes.", fx: { sieges: { reinforce: 2 } } },
  { id: "vientos_emancipacion",name:"Vientos de Emancipación",   rarity: "rara", copies: 1, text: "Todos los vasallos ganan +2 Libertad.", fx: { vassals: { pillars: { libertad: 2 } } } },
  { id: "juntas_gobierno",    name: "Juntas de Gobierno locales",rarity: "rara", copies: 1, text: "Todos los vasallos ganan +2 Poder.", fx: { vassals: { pillars: { poder: 2 } } } },
  { id: "grito_independencia",name: "Grito de Independencia",    rarity: "rara", copies: 2, text: "Inicia una guerra de liberación.", fx: { manual: true } },
  { id: "ejecucion_cabecillas",name:"Ejecución de los cabecillas rebeldes",rarity:"rara",copies:1,text:"La guerra de liberación es reprimida. Si inició por un GyG, éste muere.", fx: { manual: true } },
  { id: "toma_palacio",       name: "Toma del Palacio",          rarity: "rara", copies: 1, text: "La guerra de liberación concluye exitosamente.", fx: { manual: true } },
  { id: "mediacion_internacional",name:"Mediación Internacional",rarity:"rara", copies: 2, text: "Elige dos jugadores (incluso tú). No pueden atacarse por un turno.", fx: { manual: true } },

  /* ---------------- ÉPICAS ---------------- */
  { id: "terremoto",          name: "Terremoto Devastador",      rarity: "epica", copies: 1, text: "Destruye una ciudad a elección.", fx: { manual: true } },
  { id: "erupcion",           name: "Erupción Volcánica",        rarity: "epica", copies: 1, text: "Destruye una ciudad a elección.", fx: { manual: true } },
  { id: "motin_guarnicion",   name: "Motín de la Guarnición",    rarity: "epica", copies: 1, text: "Una ciudad se rebela con 2 cohortes rebeldes.", fx: { manual: true } },
  { id: "sesion_extraordinaria",name:"Sesión Extraordinaria",    rarity: "epica", copies: 1, text: "La próxima ronda mantiene el mismo orden de juego. No hay rotación de la mano.", fx: { global: { noRotation: true } } },
  { id: "cisma_religioso",    name: "Cisma Religioso",           rarity: "epica", copies: 1, text: "Cambia tu religión por una aleatoria.", fx: { self: { changeReligionRandom: true } } },
  { id: "crisis_regimen",     name: "Crisis de Régimen",         rarity: "epica", copies: 1, text: "Cambia tu gobierno por uno aleatorio.", fx: { self: { changeGovRandom: true } } },
  { id: "division_poderes",   name: "División de Poderes",       rarity: "epica", copies: 1, text: "Cambia tu gobierno a República (si no, aleatorio).", fx: { self: { changeGov: "republica" } } },
  { id: "coronacion_real",    name: "Coronación Real",           rarity: "epica", copies: 1, text: "Cambia tu gobierno a Monarquía (si no, aleatorio).", fx: { self: { changeGov: "monarquia" } } },
  { id: "golpe_militar",      name: "Golpe Militar",             rarity: "epica", copies: 1, text: "Cambia tu gobierno a Dictadura (si no, aleatorio).", fx: { self: { changeGov: "dictadura" } } },
  { id: "funcionarios_concurso",name:"Funcionarios por Concurso",rarity: "epica", copies: 1, text: "Cambia tu gobierno a Meritocracia (si no, aleatorio).", fx: { self: { changeGov: "meritocracia" } } },
  { id: "magos_rojos",        name: "Magos Rojos",               rarity: "epica", copies: 1, text: "Cambia tu religión a Adoradores del Fuego (si no, aleatoria).", fx: { self: { changeReligion: "fuego" } } },
  { id: "anunciacion_mesianica",name:"Anunciación Mesiánica",    rarity: "epica", copies: 1, text: "Cambia tu religión a Fe de los Profetas (si no, aleatoria).", fx: { self: { changeReligion: "profetas" } } },
  { id: "difusion_armonia",   name: "Difusión del Camino de la Armonía",rarity:"epica",copies:1,text:"Cambia tu religión a Camino de la Armonía (si no, aleatoria).", fx: { self: { changeReligion: "armonia" } } },
  { id: "resurgimiento_culto",name: "Resurgimiento del Culto al Soberano",rarity:"epica",copies:1,text:"Cambia tu religión a Culto al Soberano (si no, aleatoria).", fx: { self: { changeReligion: "soberano" } } },
];

GG.RARITY_LABEL = {
  muy_comun: "Muy común",
  comun: "Común",
  rara: "Rara",
  epica: "Épica",
};
